Ответы:
1) 1.21.5
2) 11914
3) Chevrolet, Ford, Volkswagen
4) 34
5) 5
6) No
7) 4.5949

In [1]:
!pip list

Package                       Version
----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
bea

In [145]:
import numpy as np
import pandas as pd

In [9]:
np.__version__

'1.21.5'

In [123]:
dataset = pd.read_csv('data.csv')

In [124]:
dataset.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [125]:
dataset.shape[0]

11914

In [126]:
dataset.groupby('Make').describe()

Year                                                         \
                count         mean       std     min     25%     50%     75%   
Make                                                                           
Acura           252.0  2010.063492  7.556687  1992.0  2004.0  2013.0  2016.0   
Alfa Romeo        5.0  2015.400000  0.547723  2015.0  2015.0  2015.0  2016.0   
Aston Martin     93.0  2013.021505  3.358890  2003.0  2012.0  2014.0  2015.0   
Audi            328.0  2012.231707  8.031359  1990.0  2014.0  2015.0  2016.0   
BMW             334.0  2014.347305  4.387983  1995.0  2015.0  2016.0  2016.0   
Bentley          74.0  2011.702703  4.100550  2001.0  2009.0  2013.0  2015.0   
Bugatti           3.0  2008.333333  0.577350  2008.0  2008.0  2008.0  2008.5   
Buick           196.0  2010.005102  8.038687  1990.0  2005.0  2015.0  2016.0   
Cadillac        397.0  2013.151134  5.172512  1990.0  2012.0  2015.0  2016.0   
Chevrolet      1123.0  2010.087266  7.172775  1990.0  2005.0  2015.0  2016.0   
Chrysler        187.0  2008.459893  7.653957  1990.0  2003.0  2009.0  2016.0   
Dodge           626.0  2005.440895  9.350963  1990.0  1993.0  2008.0  2015.0   
FIAT             62.0  2016.032258  0.767533  2015.0  2015.0  2016.0  2017.0   
Ferrari          69.0  2007.521739  4.729783  2001.0  2003.0  2007.0  2012.0   
Ford            881.0  2009.741203  8.036493  1990.0  2004.0  2015.0  2016.0   
GMC             515.0  2009.126214  8.270805  1990.0  2004.0  2013.0  2016.0   
Genesis           3.0  2017.000000  0.000000  2017.0  2017.0  2017.0  2017.0   
HUMMER           17.0  2009.352941  0.785905  2008.0  2009.0  2010.0  2010.0   
Honda           449.0  2013.418708  5.370904  1990.0  2014.0  2015.0  2016.0   
Hyundai         303.0  2012.696370  6.086590  1992.0  2012.0  2015.0  2016.0   
Infiniti        330.0  2010.960606  5.268617  1990.0  2009.0  2012.0  2015.0   
Kia             231.0  2013.614719  4.115036  1999.0  2011.5  2015.0  2016.0   
Lamborghini      52.0  2012.730769  2.951340  2001.0  2012.0  2014.0  2014.0   
Land Rover      143.0  2012.671329  5.340222  1994.0  2014.0  2015.0  2016.0   
Lexus           202.0  2011.623762  6.156098  1990.0  2007.0  2015.0  2016.0   
Lincoln         164.0  2011.573171  7.044173  1990.0  2006.0  2015.0  2017.0   
Lotus            29.0  2010.827586  3.485367  2002.0  2009.0  2011.0  2013.0   
Maserati         58.0  2012.775862  5.061180  2003.0  2006.0  2015.0  2016.0   
Maybach          16.0  2010.937500  0.853913  2010.0  2010.0  2011.0  2012.0   
Mazda           423.0  2008.364066  7.428639  1992.0  2001.0  2010.0  2015.0   
McLaren           5.0  2014.200000  1.643168  2012.0  2013.0  2015.0  2015.0   
Mercedes-Benz   353.0  2010.515581  9.176329  1990.0  2010.0  2015.0  2016.0   
Mitsubishi      213.0  2009.164319  7.697478  1990.0  2003.0  2012.0  2016.0   
Nissan          558.0  2012.403226  7.223077  1990.0  2014.0  2015.0  2016.0   
Oldsmobile      150.0  1997.613333  4.694401  1990.0  1994.0  1997.5  2002.0   
Plymouth         82.0  1995.463415  3.155223  1990.0  1993.0  1994.0  1999.0   
Pontiac         186.0  2003.102151  5.963429  1990.0  2001.0  2004.0  2008.0   
Porsche         136.0  2013.382353  6.927197  1990.0  2015.0  2016.0  2016.0   
Rolls-Royce      31.0  2012.516129  5.085083  2001.0  2013.0  2014.0  2015.5   
Saab            111.0  2006.081081  6.249560  1996.0  1997.5  2009.0  2011.0   
Scion            60.0  2013.416667  3.065896  2004.0  2013.0  2014.0  2015.0   
Spyker            3.0  2009.000000  0.000000  2009.0  2009.0  2009.0  2009.0   
Subaru          256.0  2011.246094  7.563456  1991.0  2007.0  2015.0  2016.0   
Suzuki          351.0  2006.310541  4.727775  1993.0  2004.0  2007.0  2011.0   
Tesla            18.0  2015.277778  0.826442  2014.0  2015.0  2015.5  2016.0   
Toyota          746.0  2012.544236  6.858595  1990.0  2014.0  2015.0  2016.0   
Volkswagen      809.0  2012.812114  5.151113  1990.0  2012.0  2015.0  2016.0   
Volvo           2

In [127]:
dataset.Make.value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [128]:
dataset.Make.value_counts().index.tolist()[:3]

['Chevrolet', 'Ford', 'Volkswagen']

In [129]:
dataset[dataset.Make == 'Audi'].head()

Make Model  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
17  Audi   100  1992  regular unleaded      172.0               6.0   
18  Audi   100  1992  regular unleaded      172.0               6.0   
19  Audi   100  1992  regular unleaded      172.0               6.0   
20  Audi   100  1992  regular unleaded      172.0               6.0   
21  Audi   100  1992  regular unleaded      172.0               6.0   

   Transmission Type      Driven_Wheels  Number of Doors Market Category  \
17            MANUAL  front wheel drive              4.0          Luxury   
18            MANUAL  front wheel drive              4.0          Luxury   
19         AUTOMATIC    all wheel drive              4.0          Luxury   
20            MANUAL  front wheel drive              4.0          Luxury   
21            MANUAL    all wheel drive              4.0          Luxury   

   Vehicle Size Vehicle Style  highway MPG  city mpg  Popularity  MSRP  
17      Midsize         Sedan           24        17        3105  2000  
18      Midsize         Sedan           24        17        3105  2000  
19      Midsize         Wagon           20        16        3105  2000  
20      Midsize         Sedan           24        17        3105  2000  
21      Midsize         Sedan           21        16        3105  2000

In [130]:
dataset[dataset.Make == 'Audi'].Model.nunique()

34

In [131]:
dataset.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [132]:
dataset['Engine Cylinders'].median()

6.0

In [133]:
frequentest = dataset['Engine Cylinders'].mode()
frequentest

0    4.0
Name: Engine Cylinders, dtype: float64

In [134]:
dataset['Engine Cylinders'].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [135]:
dataset['Engine Cylinders'] = dataset['Engine Cylinders'].fillna(int(frequentest))

In [136]:
dataset['Engine Cylinders'].median()

6.0

In [137]:
dataset.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders        0
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [138]:
dataset['Engine Cylinders'].value_counts()

4.0     4782
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [142]:
dataset[dataset['Make'] == 'Lotus'][['Engine HP', 'Engine Cylinders']].head(15)

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0

In [143]:
dataset[dataset['Make'] == 'Lotus'][['Engine HP', 'Engine Cylinders']].drop_duplicates()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [166]:
X = dataset[dataset['Make'] == 'Lotus'][['Engine HP', 'Engine Cylinders']].drop_duplicates().values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [174]:
X_transposed = X.T

In [175]:
XTX = np.dot(X_transposed, X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [176]:
inversed_XTX = np.linalg.inv(multiplicated_X_XTX)
inversed_XTX

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [177]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [179]:
w = np.dot(np.dot(inversed_XTX, X_transposed), y)
w

array([  4.59494481, -63.56432501])

In [180]:
w[0]

4.594944810094551